services:
  db:
    image: postgres
    container_name: meetcode-postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chickenjockey
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Backend-http used to be here too

  backend: #-https:
    build:
      context: ./backend
    container_name: meetcode-backend
    restart: always
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.runtime
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: ["./entrypoint-http.sh"]

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.runtime
    container_name: meetcode-frontend
    restart: always
    ports:
      - "3000:3000"  # Adjust port as needed for your frontend
    depends_on:
      - backend


  nginx:
      image: nginx:latest
      container_name: meetcode-reverse-proxy
      restart: always
      volumes:
        - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - ./reverse-proxy/certs:/etc/nginx/certs:ro
      ports:
        - "443:443"
      depends_on:
        - backend
        - frontend

volumes:
  postgres_data:
